services:
  frontend:
    container_name: frontend
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:9000"
    networks:
      - backend
    command: ["npm", "run", "dev"]

networks:
  backend:
    name: backend_backend
    external: true